services:
  app:
    build: .
    restart: always
  scheduler:
    build: .
    restart: always
    command: [ "luigid", "--pidfile", "./data/luigid.pid", "--logdir", "./data/" ]
  bundler:
    profiles: [ tools ]
    build:
      dockerfile: bundler/Dockerfile
      context: .
    volumes:
      - .:/src/:rw
