services:
  app:
    build: .
    restart: always
  scheduler:
    build: .
    restart: always
    command: [ "./venv/bin/luigid", "--pidfile", "./data/luigid.pid", "--logdir", "./data/" ]
  bundler:
    profiles: [ tools ]
    build:
      dockerfile: bundler/Dockerfile
      context: .
    pull_policy: build
    volumes:
      - ./dist:/src/dist/:rw
