services:
  app:
    # If you need access to a private GitHub repo
    #build:
    #  ssh:
    #    default: /home/.../.ssh/id_rsa
    volumes:
      - .:/var/app/
    ports:
      - "8080:8080"
  scheduler:
    volumes:
      - .:/var/app/
    ports:
      - "8082:8082"
