services:
  app:
    build: .
    environment:
      FLASK_ENV:
      FLASK_DEBUG:
      FLASK_SECRET_KEY:
    restart: always
  bundler:
    profiles: [ tools ]
    build:
      dockerfile: bundler/Dockerfile
      context: .
    volumes:
      - .:/src/:rw
